# Generated by Django 5.2.5 on 2025-09-23 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outfitcache',
            name='image',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='outfitcache',
            name='query',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
